pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - rm -rf /var/www/cloud.codeants.in/public_html/charan-rico
  - mkdir /var/www/cloud.codeants.in/public_html/charan-rico
  - cp -r public/* /var/www/cloud.codeants.in/public_html/charan-rico
  artifacts:
    paths:
    - public
  only:
  - master